// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://poiubxwfposgrcffcawp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBvaXVieHdmcG9zZ3JjZmZjYXdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3OTE0OTIsImV4cCI6MjA2OTM2NzQ5Mn0.bzvzVZkyrBI3g22YQTbsJAzq35mnW4qMO2PymcTGc_4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});